export const STATIC_PREPARATION_RESOURCES = [
  // Books
  {
    id: "r1",
    title: "Concepts of Physics by H.C. Verma",
    type: "book",
    description: "A comprehensive book for JEE and NEET physics preparation, covering theoretical concepts with practical problems.",
    url: "https://www.amazon.in/Concepts-Physics-1-H-C-Verma/dp/8177091875",
    classLevel: "11-12",
    subject: "Physics",
  },
  {
    id: "r2",
    title: "Objective Biology for NEET by Trueman",
    type: "book",
    description: "Excellent resource for deep diving into biology topics with an extensive collection of MCQs.",
    url: "https://www.amazon.in/Truemans-Objective-Biology-NEET-Vol/dp/B08V8R5Q74",
    classLevel: "11-12",
    subject: "Biology",
  },
  {
    id: "r3",
    title: "Mathematics for Class 10 by R.D. Sharma",
    type: "book",
    description: "Highly recommended for building a strong foundation in Mathematics for board exams and future competitive tests.",
    url: "https://www.amazon.in/Mathematics-Class-10-R-D-Sharma/dp/938318244X",
    classLevel: "10",
    subject: "Mathematics",
  },
  // YouTube Channels
  {
    id: "r4",
    title: "Physics Wallah - Alakh Pandey",
    type: "youtube",
    description: "Free and high-quality lectures for JEE, NEET, and board exam preparation in Hindi and English.",
    url: "https://www.youtube.com/c/PhysicsWallah",
    classLevel: "9-12",
    subject: "All Subjects",
  },
  {
    id: "r5",
    title: "Unacademy JEE",
    type: "youtube",
    description: "Live classes, tips, and strategies for cracking the JEE Main and Advanced examinations.",
    url: "https://www.youtube.com/c/UnacademyJEE",
    classLevel: "11-12",
    subject: "PCM",
  },
  // Govt Resources
  {
    id: "r6",
    title: "NCERT Official E-Books",
    type: "govt",
    description: "Download official NCERT textbooks for all subjects and classes completely free of cost.",
    url: "https://ncert.nic.in/textbook.php",
    classLevel: "6-12",
    subject: "All Subjects",
  },
  {
    id: "r7",
    title: "National Digital Library of India (NDLI)",
    type: "govt",
    description: "A virtual repository of learning resources with a single-window search facility.",
    url: "https://ndl.iitkgp.ac.in/",
    classLevel: "All",
    subject: "All Subjects",
  },
  {
    id: "r8",
    title: "DIKSHA Portal",
    type: "govt",
    description: "National Digital Infrastructure for Teachers and Students offering interactive learning content.",
    url: "https://diksha.gov.in/",
    classLevel: "1-12",
    subject: "All Subjects",
  },
  // Previous Years Papers
  {
    id: "r9",
    title: "JEE Main Previous Year Question Papers",
    type: "previous_paper",
    description: "Official JEE Main past papers with answer keys for thorough practice and pattern understanding.",
    url: "https://jeemain.nta.nic.in/past-papers/",
    classLevel: "12",
    subject: "PCM",
  },
  {
    id: "r10",
    title: "NEET Previous Year Papers",
    type: "previous_paper",
    description: "Collection of NEET UG question papers from the past 10 years.",
    url: "https://neet.nta.nic.in/previous-year-question-papers/",
    classLevel: "12",
    subject: "PCB",
  },
  // Strategy Tips
  {
    id: "r11",
    title: "How to attempt MCQs effectively?",
    type: "strategy",
    description: "Techniques like elimination, educated guessing, and time management for multiple-choice questions.",
    url: "https://example.com/mcq-strategy",
    classLevel: "All",
    subject: "General",
  },
  {
    id: "r12",
    title: "Overcoming Exam Anxiety",
    type: "strategy",
    description: "Psychological tips, breathing exercises, and preparation habits to stay calm during high-pressure exams.",
    url: "https://example.com/exam-anxiety-tips",
    classLevel: "All",
    subject: "General",
  }
];

export const STATIC_MOCK_TESTS = [
  {
    id: "t1",
    _id: "t1",
    title: "JEE Main Full Length Mock Test 1",
    examName: "JEE Main",
    type: "full_length",
    durationMinutes: 60,
    totalMarks: 10,
    questions: [
      {
        id: "q1",
        _id: "q1",
        question: "What is the unit of force?",
        options: ["Joule", "Newton", "Watt", "Pascal"],
        correctIndex: 1,
        marks: 2,
        subject: "Physics",
      },
      {
        id: "q2",
        _id: "q2",
        question: "What is the chemical formula of water?",
        options: ["H2O2", "HO", "H2O", "OH-"],
        correctIndex: 2,
        marks: 2,
        subject: "Chemistry",
      },
      {
        id: "q3",
        _id: "q3",
        question: "Find the derivative of x^2.",
        options: ["x", "2x", "x^3/3", "1"],
        correctIndex: 1,
        marks: 2,
        subject: "Mathematics",
      },
      {
        id: "q4",
        _id: "q4",
        question: "Which of the following is a noble gas?",
        options: ["Oxygen", "Nitrogen", "Argon", "Fluorine"],
        correctIndex: 2,
        marks: 2,
        subject: "Chemistry",
      },
      {
        id: "q5",
        _id: "q5",
        question: "What is the SI unit of electric current?",
        options: ["Volt", "Ohm", "Ampere", "Coulomb"],
        correctIndex: 2,
        marks: 2,
        subject: "Physics",
      }
    ]
  }
];
